/**
 * API client for backend communication
 */
import axios from 'axios'
import { toast } from 'sonner'

// Production: set VITE_API_URL (no trailing slash). Local: uses proxy /api/v1
const API_BASE_URL = (import.meta.env.VITE_API_URL || '/api/v1').replace(/\/$/, '')

const api = axios.create({
  baseURL: API_BASE_URL,
  headers: {
    'Content-Type': 'application/json',
  },
  timeout: 60000, // 60 second timeout for uploads
})

export interface FriendlyApiError {
  message: string
  original: unknown
}

/** Normalize API error detail (string, object, or array) to a single message string. */
function formatDetail(detail: unknown): string {
  if (detail == null) return ''
  if (typeof detail === 'string') return detail
  if (Array.isArray(detail)) {
    const first = detail[0]
    if (first && typeof first === 'object' && first !== null && 'msg' in first)
      return String((first as { msg?: string }).msg ?? JSON.stringify(first))
    return detail.map((d) => (typeof d === 'object' && d && 'msg' in d ? (d as { msg: string }).msg : String(d))).join('; ')
  }
  if (typeof detail === 'object' && detail !== null) {
    if ('message' in detail && typeof (detail as { message: unknown }).message === 'string')
      return (detail as { message: string }).message
    if ('msg' in detail && typeof (detail as { msg: unknown }).msg === 'string')
      return (detail as { msg: string }).msg
    return JSON.stringify(detail)
  }
  return String(detail)
}

/** Parse API/axios errors into user-friendly messages. */
export function parseError(error: unknown): FriendlyApiError {
  if (axios.isAxiosError(error)) {
    const status = error.response?.status
    const data = error.response?.data as { message?: string; detail?: unknown } | undefined
    const rawDetail = data?.detail
    const serverMessage = data?.message ?? formatDetail(rawDetail) ?? (typeof data === 'string' ? data : '')
    const msg = String(serverMessage || error.message || 'Request failed')

    if (error.code === 'ECONNABORTED' || error.message?.toLowerCase().includes('timeout')) {
      return { message: 'Request timed out. Please try again.', original: error }
    }
    if (error.message?.toLowerCase().includes('network') || error.code === 'ERR_NETWORK') {
      return { message: 'Unable to connect. Check your internet connection.', original: error }
    }
    if (status === 404) {
      return { message: "The file or resource you're looking for doesn't exist.", original: error }
    }
    if (status === 500) {
      return { message: 'Something went wrong on our end. Please try again.', original: error }
    }
    if (status === 413) {
      return { message: 'This file is too large. Maximum size is 50MB.', original: error }
    }
    if (status === 422 || status === 400) {
      return { message: serverMessage ? String(serverMessage) : 'Validation failed. Check your input.', original: error }
    }
    return { message: msg || 'Request failed. Please try again.', original: error }
  }
  const message = error instanceof Error ? error.message : 'An unexpected error occurred.'
  return { message, original: error }
}

api.interceptors.response.use(
  (response) => response,
  (error) => {
    const friendly = parseError(error)
    toast.error(friendly.message)
    return Promise.reject(friendly)
  }
)

export interface UploadResponse {
  fileId: string
  fileName: string
  sheets: string[]
}

export interface PreviewResponse {
  fileId: string
  sheetName: string
  columns: string[]
  rows: Record<string, any>[]
  headerRowIndex?: number
  warning?: string
}

export interface CellChange {
  rowIndex: number
  column: string
  oldValue: any
  newValue: any
  operationIndex: number
  operationType: string
}

export interface OperationChange {
  operationIndex: number
  operationType: string
  operationSummary: string
  cellsChanged: CellChange[]
  rowsAffected: number[]
  columnsAffected: string[]
}

export interface TransformResponse {
  fileId: string
  sheetName: string
  columns: string[]
  rows: Record<string, any>[]
  rowCountBefore: number
  rowCountAfter: number
  newColumns: string[]
  headerRowIndex?: number
  warning?: string
  changes?: OperationChange[]
}

export interface ApiError {
  error_type?: string
  column_name?: string
  available_columns?: string[]
  message?: string
  detail?: string | ApiError
}

export interface Operation {
  id?: string  // Optional: will be generated by backend if not provided
  type: 'filter' | 'replace' | 'math' | 'sort' | 'select_columns' | 'remove_duplicates' | 'aggregate' | 'text_cleanup' | 'split_column' | 'merge_columns' | 'date_format' | 'remove_blank_rows' | 'convert_to_numeric' | 'gross_profit' | 'net_profit' | 'profit_loss'
  params: Record<string, any>
}

export interface ValidationError {
  opIndex: number
  opId: string
  opType: string
  message: string
}

export interface ValidatePipelineResponse {
  ok: boolean
  errors: ValidationError[]
}

export interface MergeFilesRequest {
  fileIds: string[]
  strategy: 'append' | 'join' | 'union'
  joinColumn?: string
  joinType?: 'inner' | 'left' | 'right' | 'outer'
  headerRowIndex?: number
}

export interface MergeFilesResponse {
  mergedFileId: string
  fileName: string
  sheets: string[]
  rowCount: number
  columnCount: number
  warning?: string
}

export interface BatchTransformRequest {
  fileIds: string[]
  sheetName: string
  operations: Operation[]
  headerRowIndex?: number
  outputFormat?: 'individual' | 'zip'
}

export interface BatchTransformResult {
  fileId: string
  fileName: string
  transformedFileId?: string
  transformedFileName?: string
  rowCountBefore: number
  rowCountAfter: number
}

export interface BatchTransformResponse {
  results: BatchTransformResult[]
  zipUrl?: string
  errors?: Array<{ fileId: string; fileName: string; error: string }>
}

export interface MultipleUploadResponse {
  files: UploadResponse[]
  errors?: Array<{ fileName: string; error: string }>
}

export interface Insight {
  type: 'quality' | 'analysis'
  title: string
  description: string
  severity: 'info' | 'warning' | 'error'
  recommendation?: string
}

export interface VisualizationSuggestion {
  type: 'bar' | 'line' | 'scatter' | 'histogram' | 'pie'
  title: string
  x?: string
  y?: string
  category?: string
  value?: string
  column?: string
}

export interface AnalysisSummary {
  total_rows: number
  total_columns: number
  numeric_columns: number
  text_columns: number
  completeness: number
}

export interface AnalyzeDataRequest {
  columns: string[]
  rows: Record<string, any>[]
}

export interface AnalyzeDataResponse {
  insights: Insight[]
  visualizations: VisualizationSuggestion[]
  summary: AnalysisSummary
}

export const excelApi = {
  /**
   * Upload Excel file and get sheet names
   */
  uploadFile: async (file: File): Promise<UploadResponse> => {
    const formData = new FormData()
    formData.append('file', file)
    
    const response = await api.post<UploadResponse>('/upload-excel', formData, {
      headers: {
        'Content-Type': 'multipart/form-data',
      },
    })
    return response.data
  },

  /**
   * Preview a specific sheet
   */
  previewSheet: async (
    fileId: string,
    sheetName: string,
    limit: number = 10
  ): Promise<PreviewResponse> => {
    const response = await api.get<PreviewResponse>(
      '/preview-sheet',
      {
        params: {
          fileId: fileId,
          sheetName: sheetName,
          limit: limit,
        },
      }
    )
    return response.data
  },

  /**
   * Preview transformation with operations
   */
  previewTransform: async (
    fileId: string,
    sheetName: string,
    operations: Operation[],
    headerRowIndex?: number
  ): Promise<TransformResponse> => {
    const payload: Record<string, any> = {
      fileId,
      sheetName,
      operations,
    }
    if (headerRowIndex !== undefined) {
      payload.headerRowIndex = headerRowIndex
    }
    const response = await api.post<TransformResponse>(
      '/preview-transform',
      payload
    )
    return response.data
  },

  /**
   * Validate a transformation pipeline without applying it
   */
  validatePipeline: async (
    fileId: string,
    sheetName: string,
    operations: Operation[],
    headerRowIndex?: number
  ): Promise<ValidatePipelineResponse> => {
    const payload: Record<string, any> = {
      fileId,
      sheetName,
      operations,
    }
    if (headerRowIndex !== undefined) {
      payload.headerRowIndex = headerRowIndex
    }
    const response = await api.post<ValidatePipelineResponse>(
      '/validate-pipeline',
      payload
    )
    return response.data
  },

  /**
   * Upload multiple Excel files
   */
  uploadMultipleFiles: async (files: File[]): Promise<MultipleUploadResponse> => {
    const formData = new FormData()
    files.forEach((file) => {
      formData.append('files', file)
    })
    
    const response = await api.post<MultipleUploadResponse>('/upload-multiple-excel', formData, {
      headers: {
        'Content-Type': 'multipart/form-data',
      },
    })
    return response.data
  },

  /**
   * Merge multiple files
   */
  mergeFiles: async (request: MergeFilesRequest): Promise<MergeFilesResponse> => {
    const response = await api.post<MergeFilesResponse>('/merge-files', request)
    return response.data
  },

  /**
   * Batch transform multiple files
   */
  batchTransform: async (request: BatchTransformRequest): Promise<BatchTransformResponse> => {
    const response = await api.post<BatchTransformResponse>('/batch-transform', request)
    return response.data
  },

  /**
   * Export transformed file
   */
  exportTransform: async (
    fileId: string,
    sheetName: string,
    operations: Operation[],
    headerRowIndex?: number
  ): Promise<Blob> => {
    const payload: Record<string, any> = {
      fileId,
      sheetName,
      operations,
    }
    if (headerRowIndex !== undefined) {
      payload.headerRowIndex = headerRowIndex
    }
    const response = await api.post(
      '/export-transform',
      payload,
      { responseType: 'blob' }
    )
    return response.data
  },

  /**
   * Analyze data and return insights and visualization suggestions
   */
  analyzeData: async (request: AnalyzeDataRequest): Promise<AnalyzeDataResponse> => {
    const response = await api.post<AnalyzeDataResponse>('/analyze-data', request)
    return response.data
  },
}

export default api
